version: '3'

services:
  db:
    environment:
      - POSTGRES_DB=development
  db-admin:
    image: dpage/pgadmin4
    container_name: thor_db_admin
    ports:
      - 5400:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres
      - PGADMIN_DEFAULT_PASSWORD=qwe123
    depends_on:
      - db
    networks:
      - api-network
  api:
    environment:
      - NODE_ENV=development-docker
