---
express:
  port: 8081
logs:
  level: info
  silent: false
  node:
    meta: false
  stackDump: false
authorization:
  jwtSecret: jwt
  payloadSecret: someSecretValuePleaseChange
  tokenExpirationTime: 30days
pagination:
  limit: 10
db:
  client: postgresql
  connection:
    host: localhost
    port: 5432
    user: postgres
    password: qwe123
    database: production
  pool:
    min: 2
    max: 10
dwolla:
    key: TGgzApmT6VCbfP3CY3160dNHs4Au6Tdm0gikLxok2f8QYyffsn
    secret: xBikRTlJID8latnauamPr0oW9IlU6jeqOFBSZB5DoI6RUjEtQa
    environment: sandbox
    webhookSecret: someSecretSecret
    webhookUri: https://odin-api.gothor.com/dwolla/events
swagger:
  host: odin-api.gothor.com
  schema: https
mailer:
  mailgun:
    url: https://api.mailgun.net/v3
    domain: sandbox7e50403f173d47b992113f3287848322.mailgun.org
    key: 3fff9219ccbdd5706631dacb1d5fdb29-0e6e8cad-f2585442
    user: api
build:
  version: 0.0.5

