---
application:
  frontUri: https://odin-dev.firebaseapp.com
express:
  port: 8081
logs:
  level: info
  silent: false
  node:
    meta: false
  stackDump: false
authorization:
  jwtSecret: jwt
  payloadSecret: someSecretValuePleaseChange
  tokenExpirationTime: 30days
pagination:
  limit: 10
db:
  autoMigrate: false
  client: postgresql
  connection:
    host: localhost
    port: 5432
    user: postgres
    password: qwe123
    database: production
  pool:
    min: 2
    max: 10
dwolla:
    key: TGgzApmT6VCbfP3CY3160dNHs4Au6Tdm0gikLxok2f8QYyffsn
    secret: xBikRTlJID8latnauamPr0oW9IlU6jeqOFBSZB5DoI6RUjEtQa
    environment: sandbox
    webhookSecret: someSecretSecret
    webhookUri: https://odin-api.gothor.com/dwolla/events
    masterFunding: https://api-sandbox.dwolla.com/funding-sources/24a53f09-99ae-420d-8adc-2793845714b6
    expirationTime: 3000
    tenantId: 7bc0447a-ea99-4ba2-93bb-c84f5b325c50
swagger:
  host: odin-api.gothor.com
  schema: https
mailer:
  mailgun:
    url: https://api.mailgun.net/v3
    domain: gothor.com
    key: 7a6bfca3ea51a176c6915860175de72b-c1fe131e-16d8cc08
    user: api
build:
  version: 0.0.5

