---
express:
  port: 8081
logs:
  level: debug
  colorize: true
  filename: data/logs.log
authorization:
  jwtSecret: jwt
  tokenExpirationTime: 30days
pagination:
  limit: 10
db:
  client: postgresql
  connection:
    host: localhost
    port: 5432
    user: postgres
    password: qwe123
    database: production
  pool:
    min: 2
    max: 10
dwolla:
    key: TGgzApmT6VCbfP3CY3160dNHs4Au6Tdm0gikLxok2f8QYyffsn
    secret: xBikRTlJID8latnauamPr0oW9IlU6jeqOFBSZB5DoI6RUjEtQa
    environment: sandbox
    webhookSecret: someSecretSecret
    webhookUri: https://odin-api.gothor.com/dwolla/events
swagger:
  host: odin-api.gothor.com
  schema: https
