---
application:
  frontUri: https://odin-dev.firebaseapp.com
db:
  autoMigrate: true
  connection:
    database: development
dwolla:
  webhookUri: https://odin-api.dev.gothor.com/dwolla/events
swagger:
  host: odin-api.dev.gothor.com
  schema: https
mailer:
  override:
    to: thorodin@mailinator.com