---
application:
  frontUri: https://odin-dev.firebaseapp.com
db:
  autoMigrate: true
  connection:
    database: development
dwolla:
  webhookUri: https://odin-api.dev.gothor.com/dwolla/events
  masterFunding: https://api-sandbox.dwolla.com/funding-sources/c7a91f01-1692-4688-954d-6e785753e775
swagger:
  host: odin-api.dev.gothor.com
  schema: https
mailer:
  override:
    to: thorodin@mailinator.com
