---
application:
  frontUri: https://odin-sandbox.gothor.com
db:
  autoMigrate: true
  connection:
    database: sandbox
swagger:
  host: odin-api.sand.gothor.com
  schema: https
mailer:
  override:
    to: thorodin@mailinator.com
