---
application:
  frontUri: https://odin-dev.firebaseapp.com
db:
  autoMigrate: true
  connection:
    host: 35.233.154.25
    password: bzm1tdHrM7C9hNdj
    database: development
dwolla:
  webhookUri: https://odin-api.dev.gothor.com/dwolla/events
swagger:
  host: odin-api.dev.gothor.com
  schema: https
# mailer:
#   override:
#     to: test.acsft@gmail.com
#   mailgun:
#     domain: sandboxe0ca2f8eaed14f5a938c9738a3858206.mailgun.org
#     key: 7a6bfca3ea51a176c6915860175de72b-c1fe131e-16d8cc08