---
application:
  frontUri: https://odin-sandbox.gothor.com
db:
  autoMigrate: true
  connection:
    database: stage
dwolla:
  webhookUri: https://odin-api.stg.gothor.com/dwolla/events
  masterFunding: https://api-sandbox.dwolla.com/funding-sources/6fa23d1d-03a2-49df-b8eb-c577848786e3
swagger:
  host: odin-api.stg.gothor.com
  schema: https
storage:
  bucket: thor-stg
mailer:
  override:
    to: thorodin@mailinator.com
