---
application:
  frontUri: https://odin-dev.firebaseapp.com
db:
  connection:
    host: 35.233.154.25
    password: bzm1tdHrM7C9hNdj
    database: dev2
dwolla:
  webhookUri: https://odin-api.dev.gothor.com/dwolla/events
swagger:
  host: odin-api.dev.gothor.com
  schema: https