---
application:
  frontUri: https://odin.gothor.com
db:
  autoMigrate: true
  connection:
    database: production
dwolla:
  webhookUri: https://odin-api.prod.gothor.com/dwolla/events
  environment: production
  masterFunding: https://api.dwolla.com/funding-sources/5f8bb320-4beb-40e9-ba6c-db977fc8f476
swagger:
  host: odin-api.prod.gothor.com
  schema: https
storage:
  bucket: thor-prod

