apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "thor-api.fullname" . }}
  labels:
    app: {{ template "thor-api.name" . }}
    chart: {{ template "thor-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "thor-api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "thor-api.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.env.DOCKER_REPOSITORY }}:{{ .Values.env.TAG }}"
          command: ["npm"]
          args: ["start"]
          env:
            - name: NODE_ENV
              value: {{ .Values.app.nodeEnv }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
