apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "thor-api.fullname" . }}
  labels:
    app: {{ template "thor-api.name" . }}
    chart: {{ template "thor-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "thor-api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "thor-api.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: "google-cloud-key"
          secret:
            secretName: "storage-key"
      containers:
        - name: "{{ .Chart.Name }}-app"
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
              readOnly: true
          image: "{{ .Values.env.DOCKER_REPOSITORY }}:{{ .Values.env.TAG }}"
          command: ["npm"]
          args: ["start"]
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: credentials
          env:
            - name: NODE_ENV
              value: {{ .Values.app.nodeEnv }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
