apiVersion: v1
kind: Service
metadata:
  name: "thor-api-backend"
  labels:
    app: {{ template "thor-api.name" . }}
    chart: {{ template "thor-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ template "thor-api.name" . }}
    release: {{ .Release.Name }}
