apiVersion: v1
kind: Service
metadata:
  name: {{ template "thor-api.fullname" . }}
  labels:
    app: {{ template "thor-api.name" . }}
    chart: {{ template "thor-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ template "thor-api.name" . }}
    release: {{ .Release.Name }}
